# Generated by Django 4.2.5 on 2023-12-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, null=True, verbose_name='Titre du poste')),
                ('entreprise_name', models.CharField(max_length=200, null=True, verbose_name="Nom de l'entreprise")),
                ('entreprise_location', models.CharField(max_length=50, null=True, verbose_name='Localisation')),
                ('reference', models.CharField(default='Ayd2023', max_length=20, verbose_name='Reference')),
                ('job_duration', models.CharField(choices=[('Sur site', 'Sur site'), ('En ligne', 'En ligne')], default='Temporaire', max_length=10, verbose_name='Contrat')),
                ('job_type2', models.CharField(choices=[('Temps plein', 'Temps plein'), ('Temps partiel', 'Temps partiel')], default='Temps plein', max_length=15, verbose_name='Horaire')),
                ('job_type', models.CharField(choices=[('Temporaire', 'Temporaire'), ('Permanent', 'Permanent')], default='Sur site', max_length=10, verbose_name="Type d'emploi")),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('responsabilities', models.TextField(blank=True, max_length=500, null=True, verbose_name='Responsabilités')),
                ('qualifications', models.TextField(blank=True, max_length=500, null=True, verbose_name='Qualifications')),
                ('deadline', models.DateField(null=True, verbose_name='Dernier délai')),
                ('close', models.BooleanField(default=False, null=True, verbose_name='Dossier fermé')),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de publication')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('content', models.CharField(max_length=500)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
